name: goldencheetah
version: '3.4.0'
summary: GoldenCheetah is a data analysis tool for cyclists and triathletes
description: |
  GoldenCheetah is an open-source data analysis tool primarily written in C++ with Qt for cyclists
  and triathletes with support for training as well.
  GoldenCheetah can connect with indoor trainers and cycling equipment such as cycling computers
  and power meters to import data. In addition, GoldenCheetah can connect to cloud services.
  It can then manipulate and view the data, as well as analyze it.
grade: stable
confinement: strict
#icon: usr/share/pixmaps/gc.png
apps:
  GoldenCheetah:
    command: desktop-launch $SNAP/opt/GoldenCheetah/GoldenCheetah
    #desktop: $SNAP/usr/share/applications/GoldenCheetah.desktop
    plugs:
      - home
      - x11
      #- wayland
      - desktop
      #- desktop-legacy
      - unity7
      - browser-support
      - opengl
      - network
      - network-bind
      - removable-media
      - raw-usb

parts:
  goldencheetah:
    source: https://github.com/GoldenCheetah/GoldenCheetah.git
    source-tag: release_3.4.0
    plugin: qmake
    qt-version: qt5
    after: [desktop-qt5] # see https://github.com/Ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
    build-packages:
      - libqt5svg5-dev
      - libqt5webkit5-dev
      - libqt5serialport5-dev
      - qtmultimedia5-dev
      - qtconnectivity5-dev
      - libssl-dev
      - bison
      - flex
    stage-packages:
      - libicu55
      - libqt5bluetooth5
      - libqt5concurrent5
      - libqt5dbus5
      #- libqt5gui5 # present in desktop-qt5
      - libqt5multimedia5
      - libqt5multimediawidgets5
      - libqt5network5
      - libqt5opengl5
      - libqt5positioning5
      - libqt5printsupport5
      - libqt5qml5
      - libqt5quick5
      - libqt5sensors5
      - libqt5serialport5
      - libqt5sql5
      - libqt5sql5-sqlite
      #- libqt5svg5 # present in desktop-qt5
      #- libqt5webchannel5 # not present in ubuntu 16.04
      - libqt5webkit5
      - libqt5widgets5
      - libqt5xml5
      - r-cran-rinside
      - libsamplerate0
      - openssl
      - libusb-1.0-0
      - vlc
      - r-base-core
      - libglu1-mesa
      - libgstreamer0.10-0
      - libgstreamer-plugins-base0.10-0
      - gawk
    prepare: |
      cp qwt/qwtconfig.pri.in qwt/qwtconfig.pri
      cp src/gcconfig.pri.in src/gcconfig.pri
      sed -i "s|#\(CONFIG += release.*\)|\1 static|" src/gcconfig.pri
      sed -i "s|#\(QMAKE_LRELEASE = \).*|\1 lrelease|" src/gcconfig.pri
      sed -i "s|^#DESTDIR|DESTDIR|" src/gcconfig.pri
      sed -i "s|^#OBJECTS_DIR|OBJECT_DIR|" src/gcconfig.pri
      sed -i "s|^#MOC_DIR|MOC_DIR|" src/gcconfig.pri
      sed -i "s|^#RCC_DIR|RCC_DIR|" src/gcconfig.pri
      sed -i "s|^#UI_DIR|UI_DIR|" src/gcconfig.pri
      sed -i "s|^#LIBZ_LIBS|LIBZ_LIBS|" src/gcconfig.pri
      # TODO: add vlc and other missing options to src/gcconfig.pri
    build: |
      export QT_SELECT=5
      qmake -recursive
      make -j4
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/GoldenCheetah
      cp src/GoldenCheetah $SNAPCRAFT_PART_INSTALL/opt/GoldenCheetah/
      #ln -fs $SNAPCRAFT_PART_INSTALL/opt/GoldenCheetah/GoldenCheetah $SNAPCRAFT_PART_INSTALL/usr/bin/GoldenCheetah
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/udev/rules.d
      cp src/Resources/linux/*.rules $SNAPCRAFT_PART_INSTALL/etc/udev/rules.d
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      cp src/Resources/images/gc.png $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      $SNAPCRAFT_PART_INSTALL/usr/lib/vlc/vlc-cache-gen --force $SNAPCRAFT_PART_INSTALL/usr/lib/vlc/plugins/

  # TODO: find a way to compile qtwebchannel
  #qtwebchannel:
  #  source: git://code.qt.io/qt/qtwebchannel.git
  #  source-tag: v5.9.4
  #  plugin: qmake
  #  qt-version: qt5
  # after: [goldencheetah]

  # Additional files (GoldenCheetah.desktop and libQt5WebChannel)
  misc-files:
    source: files/
    plugin: dump
    after: [goldencheetah]
    install: |
      ln -fs $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5.9.4 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5.9
      ln -fs $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5.9.4 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5
